const express = require('express')
const cors = require('cors')
const multer = require('multer')
const path = require('path')
const userRoutes = require('./routes/userRoutes')
const app = express()
app.use(cors())
app.use(express.json())
app.use('/uploads', express.static(path.join(__dirname, 'uploads')))
app.use('/api/users', userRoutes)
app.listen(5000, () => console.log('Server running on port 5000'))
